postgres:
  name: "argus_events"
  host: "localhost"
  port: "6432"
  user: "postgres"
  password: "postgres"

postgres_tango:
  name: "argus_prod_logcat"
  host: "localhost"
  port: "6432"
  user: "postgres"
  password: "postgres"

  

